#!/usr/bin/env python3
"""Generate a random bot version name and write it to shared/version.py.

Called by .git/hooks/pre-commit on every commit so each deployed version
has a unique human-readable identifier traceable in git history and the DB.
"""
import os
import random

ADJECTIVES = [
    "amber", "arctic", "blazing", "bold", "brave", "calm", "clever", "crimson",
    "crystal", "dark", "dusk", "fierce", "frozen", "ghost", "gilded", "iron",
    "jade", "lunar", "mighty", "mystic", "neon", "noble", "obsidian", "onyx",
    "phantom", "quantum", "rapid", "rogue", "royal", "rustic", "sacred", "scarlet",
    "shadow", "silent", "silver", "solar", "sonic", "steel", "storm", "swift",
    "titan", "turbo", "ultra", "velvet", "violet", "vivid", "wild", "winter",
]

NOUNS = [
    "badger", "bear", "bobcat", "cobra", "condor", "coyote", "crane", "dingo",
    "dragon", "eagle", "falcon", "ferret", "fox", "gecko", "hawk", "heron",
    "jaguar", "kestrel", "lynx", "mamba", "mantis", "marlin", "mongoose", "osprey",
    "otter", "panda", "panther", "phoenix", "pike", "puma", "raven", "reef",
    "rhino", "sable", "shark", "sparrow", "sphinx", "stallion", "starling", "tiger",
    "viper", "walrus", "warden", "weasel", "whale", "wolf", "wolverine", "wren",
]


def generate_version() -> str:
    adj = random.choice(ADJECTIVES)
    noun = random.choice(NOUNS)
    num = random.randint(10, 99)
    return f"{adj}-{noun}-{num}"


def main():
    version = generate_version()
    out_path = os.path.join(os.path.dirname(__file__), "..", "shared", "version.py")
    out_path = os.path.normpath(out_path)
    with open(out_path, "w") as f:
        f.write("# Auto-generated by scripts/gen_version.py on each git commit.\n")
        f.write("# Do not edit manually — run `python scripts/gen_version.py` to regenerate.\n")
        f.write(f'BOT_VERSION = "{version}"\n')
    print(f"Bot version: {version}")


if __name__ == "__main__":
    main()
